### ISSUE TITLE
Ghost in the lights

### ISSUE THREAD

**Issue by fcassata** [fredck/lightener#120]
I have 16 WiZ bulbs set up in one lightener device. All of which have 4 mapping lines, allowing me to gradually turn them on one by one, and then gradually increase brightness slowly. 

When it works it's great, but after setting this up, the lights change brightness on their own every few minutes, always down, until they eventually turn off. The mapping config also slowly drifts "off", so that 100% on the lightener device seems to only go to about 30% on the config.

The automation that connects the wireless rotary dimmer to the light is not being triggered when the dimming happens, and there is nothing in the logs. I've turned on debug logging for the integration, but nothing their either.

Any ideas?

**Comment by fcassata** [comment]
User reports same issue in [a reddit thread,](https://www.reddit.com/r/homeassistant/comments/1ahvo2a/anyone_familiar_with_the_lightener_hacs/) so probably not particular to my setup.

**Comment by fredck** [comment]
I think I have faced something similar myself. It was tricky to debug the problem though and I figured a workaround **that worked for me**_._

In my case, it felt like the Lightner configuration got messed up during HA (re)load. The following automation stabilized everything:

```
alias: Reload Lightener configurations on Home Assistant start
description: ""
trigger:
  - platform: homeassistant
    event: start
condition: []
action:
  - service: homeassistant.reload_config_entry
    data: {}
    target:
      entity_id:
        - light.living_room
        - light.dining_room
        - light.kitchen
        - light.club
        - light.hall
        - light.stairs
        - light.office
        - light.eduardo
        - light.ewa
        - light.riki
        - light.kids_bathroom
        - light.master_bedroom
        - light.master_bathroom
        - light.closet
        - light.cinema
mode: single
```

If I remember well, I believe I was seeing this problem in rooms with many lights. Maybe you're seeing the same with your 16 bulbs.

I hope someone else can confirm tha this automation helps. It could give hints on what's the cause of this issue bucause, in any case, we need a reliable way to reproduce the problem before we even try to fix it.

**Comment by fcassata** [comment]
Thanks, I'll see if this makes a difference in my case.

**Comment by fcassata** [comment]
No change with the proposed workaround, here is my 16 bulb config in case it helps...

`
  {
    "entry_id": "7579a8ab4410a2532461a2cd5ad2a1fb",
    "version": 2,
    "minor_version": 1,
    "domain": "lightener",
    "title": "Svefnherbergi_Loftljós",
    "data": {
      "friendly_name": "Svefnherbergi_Loftljós",
      "entities": {
        "light.wiz_dandelion_1": {
          "brightness": {
            "1": "1",
            "60": "1",
            "100": "50"
          }
        },
        "light.wiz_dandelion_2": {
          "brightness": {
            "1": "0",
            "5": "0",
            "60": "1",
            "100": "50"
          }
        },
        "light.wiz_dandelion_3": {
          "brightness": {
            "1": "0",
            "10": "0",
            "60": "1",
            "100": "50"
          }
        },
        "light.wiz_dandelion_4": {
          "brightness": {
            "1": "0",
            "15": "0",
            "65": "1",
            "100": "50"
          }
        },
        "light.wiz_dandelion_5": {
          "brightness": {
            "1": "0",
            "20": "0",
            "65": "1",
            "100": "50"
          }
        },
        "light.wiz_dandelion_6": {
          "brightness": {
            "1": "0",
            "22": "0",
            "65": "1",
            "100": "50"
          }
        },
        "light.wiz_dandelion_7": {
          "brightness": {
            "1": "0",
            "25": "0",
            "70": "1",
            "100": "50"
          }
        },
        "light.wiz_dandelion_8": {
          "brightness": {
            "1": "0",
            "28": "0",
            "70": "1",
            "100": "50"
          }
        },
        "light.wiz_dandelion_9": {
          "brightness": {
            "1": "0",
            "30": "0",
            "70": "1",
            "100": "50"
          }
        },
        "light.wiz_dandelion_10": {
          "brightness": {
            "1": "0",
            "35": "0",
            "70": "1",
            "100": "50"
          }
        },
        "light.wiz_dandelion_11": {
          "brightness": {
            "1": "0",
            "40": "0",
            "70": "1",
            "100": "50"
          }
        },
        "light.wiz_dandelion_12": {
          "brightness": {
            "1": "0",
            "42": "0",
            "70": "1",
            "100": "50"
          }
        },
        "light.wiz_dandelion_13": {
          "brightness": {
            "1": "0",
            "45": "0",
            "75": "1",
            "100": "50"
          }
        },
        "light.wiz_dandelion_14": {
          "brightness": {
            "1": "0",
            "50": "0",
            "75": "1",
            "100": "50"
          }
        },
        "light.wiz_dandelion_15": {
          "brightness": {
            "1": "0",
            "52": "0",
            "75": "1",
            "100": "50"
          }
        },
        "light.wiz_dandelion_16": {
          "brightness": {
            "1": "0",
            "55": "0",
            "75": "1",
            "100": "50"
          }
        }
      }
    },
`

**Comment by fcassata** [comment]
Having given it some time, I believe the automation workaround is making it somewhat more stable. It is definitely usable now with the occasional quirk. Thank you @fredck

**Comment by fredck** [comment]
If that's the case, you may try using the "Reload" option of the specific Lightener configuration in your system at https://my.home-assistant.io/redirect/integration/?domain=lightener when this situation happens.

If this really helps, it can give us some hints that could help figure this thing out. Thanks!

**Comment by fredck** [comment]
@fcassata Are you able to give a try to [Lightener v2.3.0-beta.3](https://github.com/fredck/lightener/releases/tag/v2.3.0-beta.3) and see if there is any improvement. This is a pre-release so HACS doesn't install it by default but it gives you the option to install it ("redownload").

This release has lots of small improvements and I have hope that they may help. Also, it comes now with a lot of debug logging. If your problem persists, please enable debug logging in your ha configuration:

```yaml
logger:
  default: info
  logs:
    custom_components.lightener: debug
```

Then, play with the lights and see what your logs says (check the log file directly, not the log page). You may find something helpful there. You can even attach some logs here.

As you can imagine it is very difficult to reproduce your specific use case. It may be related to the lights themselves. I really hope this release can help us figuring this out.

Thanks!
